language: ruby

script: bundle exec rake

rvm:
  - 2.1
  - 2.0
  - 1.9
gemfile:
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile

matrix:
  include:
    - rvm: 2.2
      gemfile:
        - gemfiles/5.1.gemfile